// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: chats.proto

package chats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LastReadMessagesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastReadMessagesReq) Reset() {
	*x = LastReadMessagesReq{}
	mi := &file_chats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastReadMessagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastReadMessagesReq) ProtoMessage() {}

func (x *LastReadMessagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_chats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastReadMessagesReq.ProtoReflect.Descriptor instead.
func (*LastReadMessagesReq) Descriptor() ([]byte, []int) {
	return file_chats_proto_rawDescGZIP(), []int{0}
}

func (x *LastReadMessagesReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type LastReadMessagesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Err           *Error                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastReadMessagesResp) Reset() {
	*x = LastReadMessagesResp{}
	mi := &file_chats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastReadMessagesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastReadMessagesResp) ProtoMessage() {}

func (x *LastReadMessagesResp) ProtoReflect() protoreflect.Message {
	mi := &file_chats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastReadMessagesResp.ProtoReflect.Descriptor instead.
func (*LastReadMessagesResp) Descriptor() ([]byte, []int) {
	return file_chats_proto_rawDescGZIP(), []int{1}
}

func (x *LastReadMessagesResp) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *LastReadMessagesResp) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastMessageID string                 `protobuf:"bytes,1,opt,name=lastMessageID,proto3" json:"lastMessageID,omitempty"`
	ChatID        int64                  `protobuf:"varint,2,opt,name=chatID,proto3" json:"chatID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_chats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_chats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_chats_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetLastMessageID() string {
	if x != nil {
		return x.LastMessageID
	}
	return ""
}

func (x *Message) GetChatID() int64 {
	if x != nil {
		return x.ChatID
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_chats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_chats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_chats_proto_rawDescGZIP(), []int{3}
}

func (x *Error) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_chats_proto protoreflect.FileDescriptor

const file_chats_proto_rawDesc = "" +
	"\n" +
	"\vchats.proto\x12\x05chats\"-\n" +
	"\x13LastReadMessagesReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x03R\x06userID\"b\n" +
	"\x14LastReadMessagesResp\x12*\n" +
	"\bmessages\x18\x01 \x03(\v2\x0e.chats.MessageR\bmessages\x12\x1e\n" +
	"\x03err\x18\x02 \x01(\v2\f.chats.ErrorR\x03err\"G\n" +
	"\aMessage\x12$\n" +
	"\rlastMessageID\x18\x01 \x01(\tR\rlastMessageID\x12\x16\n" +
	"\x06chatID\x18\x02 \x01(\x03R\x06chatID\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2V\n" +
	"\x05Chats\x12M\n" +
	"\x10LastReadMessages\x12\x1a.chats.LastReadMessagesReq\x1a\x1b.chats.LastReadMessagesResp\"\x00B\x0eZ\fapi/pb/chatsb\x06proto3"

var (
	file_chats_proto_rawDescOnce sync.Once
	file_chats_proto_rawDescData []byte
)

func file_chats_proto_rawDescGZIP() []byte {
	file_chats_proto_rawDescOnce.Do(func() {
		file_chats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chats_proto_rawDesc), len(file_chats_proto_rawDesc)))
	})
	return file_chats_proto_rawDescData
}

var file_chats_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_chats_proto_goTypes = []any{
	(*LastReadMessagesReq)(nil),  // 0: chats.LastReadMessagesReq
	(*LastReadMessagesResp)(nil), // 1: chats.LastReadMessagesResp
	(*Message)(nil),              // 2: chats.Message
	(*Error)(nil),                // 3: chats.Error
}
var file_chats_proto_depIdxs = []int32{
	2, // 0: chats.LastReadMessagesResp.messages:type_name -> chats.Message
	3, // 1: chats.LastReadMessagesResp.err:type_name -> chats.Error
	0, // 2: chats.Chats.LastReadMessages:input_type -> chats.LastReadMessagesReq
	1, // 3: chats.Chats.LastReadMessages:output_type -> chats.LastReadMessagesResp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_chats_proto_init() }
func file_chats_proto_init() {
	if File_chats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chats_proto_rawDesc), len(file_chats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chats_proto_goTypes,
		DependencyIndexes: file_chats_proto_depIdxs,
		MessageInfos:      file_chats_proto_msgTypes,
	}.Build()
	File_chats_proto = out.File
	file_chats_proto_goTypes = nil
	file_chats_proto_depIdxs = nil
}
