services:

  projects-database:
    build:
      dockerfile: Dockerfile
      context: ./databases/postgres_db
      args:
        SERVICE: "projects"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/projects-database-secret
    secrets:
      - projects-database-secret
    volumes:
      - projects_volume:/var/lib/postgresql/data

  users-database:
    build:
      dockerfile: Dockerfile
      context: ./databases/postgres_db/
      args:
        SERVICE: "users"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/users-database-secret
    secrets:
      - users-database-secret
    volumes:
      - users_volume:/var/lib/postgresql/data
  
  chats-database:
    build:
      dockerfile: Dockerfile
      context: ./databases/postgres_db/
      args:
        SERVICE: "chats"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/chats-database-secret
    secrets:
      - chats-database-secret
    volumes:
      - chats_volume:/var/lib/postgresql/data
  
  mongo1:
    build: ./databases/mongo_db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs1',members:[{_id:0,host:'mongo1:27017'}]}) }" | mongosh --port 27017 -u mongo -p "$$(cat /run/secrets/mongodb-secret)"
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    environment:
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb-secret
    secrets:
      - mongodb-secret
      - mongodb-internal-secret
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"
  
  frontend:
    build: 
      dockerfile: ./social-media/deployments/frontend/Dockerfile
      context: ../../
    ports:
      - "8080:8080"
  
  log:
    build:
      dockerfile: ./deployments/services/Dockerfile.2port
      context: ..
      args:
        SERVICE: "log"
        FIRST_PORT: "8090"
        SECOND_PORT: "8084"
    ports:
      - "8084:8084"
      - "8090:8090"
  
  auth:
    build:
      dockerfile: ./deployments/services/Dockerfile
      context: ..
      args:
        SERVICE: "authentication"
        PORT: "8085"
    ports:
      - "8085:8085"
    secrets:
      - key
    depends_on:
      - log
  
  projects:
    build:
      dockerfile: ./deployments/services/Dockerfile
      context: ..
      args:
        SERVICE: "projects"
        PORT: "8086"
    ports:
      - "8086:8086"
    secrets:
      - projects-database-secret
    depends_on:
      - log
      - auth
      - projects-database
  
  chats:
    build:
      dockerfile: ./deployments/services/Dockerfile
      context: ..
      args:
        SERVICE: "chats"
        PORT: "8083"
    ports:
      - "8083:8083"
    secrets:
      - chats-database-secret
    depends_on:
      - log
      - auth
      - chats-database

  posts:
    build:
      dockerfile: ./deployments/services/Dockerfile.2port
      context: ..
      args:
        SERVICE: "posts"
        FIST_PORT: "8082"
        SECOND_PORT: "8088"
    ports:
      - "8082:8082"
      - "8088:8088"
    secrets:
      - mongodb-secret
    depends_on:
      - mongo1
      - log
      - auth
      - chats
      - ai
    volumes:
      - "files_volume:/cmd/upload"
  
  ai:
    build:
      dockerfile: ./deployments/services/Dockerfile.gunicorn
      context: ..
    ports:
      - "8000:8000"

  users:
    build:
      dockerfile: ./deployments/services/Dockerfile.2port
      context: ..
      args:
        SERVICE: "users"
        FIST_PORT: "8081"
        SECOND_PORT: "8087"
    ports:
      - "8081:8081"
      - "8087:8087"
    secrets:
      - users-database-secret
    depends_on:
      - log
      - auth
      - users-database

volumes:
  projects_volume:
  users_volume:
  chats_volume:
  mongo1_data:
  mongo1_config:
  files_volume:

secrets:
  key:
    file: ./secrets/key.txt
  mongodb-secret:
    file: ./secrets/mongodb.txt
  mongodb-internal-secret:
    file: ./secrets/mongodb-internal-secret.txt
  users-database-secret:
    file: ./secrets/users-database.txt
  chats-database-secret:
    file: ./secrets/chats-database.txt
  projects-database-secret:
    file: ./secrets/projects-database.txt