// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateJWTReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateJWTReq) Reset() {
	*x = GenerateJWTReq{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateJWTReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateJWTReq) ProtoMessage() {}

func (x *GenerateJWTReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateJWTReq.ProtoReflect.Descriptor instead.
func (*GenerateJWTReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateJWTReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GenerateJWTReq) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type GenerateJWTResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Err           *Error                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateJWTResp) Reset() {
	*x = GenerateJWTResp{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateJWTResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateJWTResp) ProtoMessage() {}

func (x *GenerateJWTResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateJWTResp.ProtoReflect.Descriptor instead.
func (*GenerateJWTResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateJWTResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GenerateJWTResp) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

type ValidateJWTReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateJWTReq) Reset() {
	*x = ValidateJWTReq{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateJWTReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateJWTReq) ProtoMessage() {}

func (x *ValidateJWTReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateJWTReq.ProtoReflect.Descriptor instead.
func (*ValidateJWTReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateJWTReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateJWTResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Err           *Error                 `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateJWTResp) Reset() {
	*x = ValidateJWTResp{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateJWTResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateJWTResp) ProtoMessage() {}

func (x *ValidateJWTResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateJWTResp.ProtoReflect.Descriptor instead.
func (*ValidateJWTResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateJWTResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ValidateJWTResp) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ValidateJWTResp) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *Error) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GenerateSignedUrlReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileID        string                 `protobuf:"bytes,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSignedUrlReq) Reset() {
	*x = GenerateSignedUrlReq{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSignedUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSignedUrlReq) ProtoMessage() {}

func (x *GenerateSignedUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSignedUrlReq.ProtoReflect.Descriptor instead.
func (*GenerateSignedUrlReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateSignedUrlReq) GetFileID() string {
	if x != nil {
		return x.FileID
	}
	return ""
}

type GenerateSignedUrlResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Err           *Error                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSignedUrlResp) Reset() {
	*x = GenerateSignedUrlResp{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSignedUrlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSignedUrlResp) ProtoMessage() {}

func (x *GenerateSignedUrlResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSignedUrlResp.ProtoReflect.Descriptor instead.
func (*GenerateSignedUrlResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateSignedUrlResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GenerateSignedUrlResp) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

type ValidateSignedUrlReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSignedUrlReq) Reset() {
	*x = ValidateSignedUrlReq{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSignedUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSignedUrlReq) ProtoMessage() {}

func (x *ValidateSignedUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSignedUrlReq.ProtoReflect.Descriptor instead.
func (*ValidateSignedUrlReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateSignedUrlReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateSignedUrlResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileID        string                 `protobuf:"bytes,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	Err           *Error                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSignedUrlResp) Reset() {
	*x = ValidateSignedUrlResp{}
	mi := &file_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSignedUrlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSignedUrlResp) ProtoMessage() {}

func (x *ValidateSignedUrlResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSignedUrlResp.ProtoReflect.Descriptor instead.
func (*ValidateSignedUrlResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateSignedUrlResp) GetFileID() string {
	if x != nil {
		return x.FileID
	}
	return ""
}

func (x *ValidateSignedUrlResp) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x04auth\"6\n" +
	"\x0eGenerateJWTReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\"F\n" +
	"\x0fGenerateJWTResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\x03err\x18\x02 \x01(\v2\v.auth.ErrorR\x03err\"&\n" +
	"\x0eValidateJWTReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"V\n" +
	"\x0fValidateJWTResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x1d\n" +
	"\x03err\x18\x03 \x01(\v2\v.auth.ErrorR\x03err\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\".\n" +
	"\x14GenerateSignedUrlReq\x12\x16\n" +
	"\x06fileID\x18\x01 \x01(\tR\x06fileID\"L\n" +
	"\x15GenerateSignedUrlResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\x03err\x18\x02 \x01(\v2\v.auth.ErrorR\x03err\",\n" +
	"\x14ValidateSignedUrlReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"N\n" +
	"\x15ValidateSignedUrlResp\x12\x16\n" +
	"\x06fileID\x18\x01 \x01(\tR\x06fileID\x12\x1d\n" +
	"\x03err\x18\x02 \x01(\v2\v.auth.ErrorR\x03err2\xaa\x02\n" +
	"\fAuthenticate\x12<\n" +
	"\vGenerateJWT\x12\x14.auth.GenerateJWTReq\x1a\x15.auth.GenerateJWTResp\"\x00\x12<\n" +
	"\vValidateJWT\x12\x14.auth.ValidateJWTReq\x1a\x15.auth.ValidateJWTResp\"\x00\x12N\n" +
	"\x11GenerateSignedUrl\x12\x1a.auth.GenerateSignedUrlReq\x1a\x1b.auth.GenerateSignedUrlResp\"\x00\x12N\n" +
	"\x11ValidateSignedUrl\x12\x1a.auth.ValidateSignedUrlReq\x1a\x1b.auth.ValidateSignedUrlResp\"\x00B\rZ\vapi/pb/authb\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_auth_proto_goTypes = []any{
	(*GenerateJWTReq)(nil),        // 0: auth.GenerateJWTReq
	(*GenerateJWTResp)(nil),       // 1: auth.GenerateJWTResp
	(*ValidateJWTReq)(nil),        // 2: auth.ValidateJWTReq
	(*ValidateJWTResp)(nil),       // 3: auth.ValidateJWTResp
	(*Error)(nil),                 // 4: auth.Error
	(*GenerateSignedUrlReq)(nil),  // 5: auth.GenerateSignedUrlReq
	(*GenerateSignedUrlResp)(nil), // 6: auth.GenerateSignedUrlResp
	(*ValidateSignedUrlReq)(nil),  // 7: auth.ValidateSignedUrlReq
	(*ValidateSignedUrlResp)(nil), // 8: auth.ValidateSignedUrlResp
}
var file_auth_proto_depIdxs = []int32{
	4, // 0: auth.GenerateJWTResp.err:type_name -> auth.Error
	4, // 1: auth.ValidateJWTResp.err:type_name -> auth.Error
	4, // 2: auth.GenerateSignedUrlResp.err:type_name -> auth.Error
	4, // 3: auth.ValidateSignedUrlResp.err:type_name -> auth.Error
	0, // 4: auth.Authenticate.GenerateJWT:input_type -> auth.GenerateJWTReq
	2, // 5: auth.Authenticate.ValidateJWT:input_type -> auth.ValidateJWTReq
	5, // 6: auth.Authenticate.GenerateSignedUrl:input_type -> auth.GenerateSignedUrlReq
	7, // 7: auth.Authenticate.ValidateSignedUrl:input_type -> auth.ValidateSignedUrlReq
	1, // 8: auth.Authenticate.GenerateJWT:output_type -> auth.GenerateJWTResp
	3, // 9: auth.Authenticate.ValidateJWT:output_type -> auth.ValidateJWTResp
	6, // 10: auth.Authenticate.GenerateSignedUrl:output_type -> auth.GenerateSignedUrlResp
	8, // 11: auth.Authenticate.ValidateSignedUrl:output_type -> auth.ValidateSignedUrlResp
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
