// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Authenticate_GenerateJWT_FullMethodName       = "/auth.Authenticate/GenerateJWT"
	Authenticate_ValidateJWT_FullMethodName       = "/auth.Authenticate/ValidateJWT"
	Authenticate_GenerateSignedUrl_FullMethodName = "/auth.Authenticate/GenerateSignedUrl"
	Authenticate_ValidateSignedUrl_FullMethodName = "/auth.Authenticate/ValidateSignedUrl"
)

// AuthenticateClient is the client API for Authenticate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthenticateClient interface {
	GenerateJWT(ctx context.Context, in *GenerateJWTReq, opts ...grpc.CallOption) (*GenerateJWTResp, error)
	ValidateJWT(ctx context.Context, in *ValidateJWTReq, opts ...grpc.CallOption) (*ValidateJWTResp, error)
	GenerateSignedUrl(ctx context.Context, in *GenerateSignedUrlReq, opts ...grpc.CallOption) (*GenerateSignedUrlResp, error)
	ValidateSignedUrl(ctx context.Context, in *ValidateSignedUrlReq, opts ...grpc.CallOption) (*ValidateSignedUrlResp, error)
}

type authenticateClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticateClient(cc grpc.ClientConnInterface) AuthenticateClient {
	return &authenticateClient{cc}
}

func (c *authenticateClient) GenerateJWT(ctx context.Context, in *GenerateJWTReq, opts ...grpc.CallOption) (*GenerateJWTResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateJWTResp)
	err := c.cc.Invoke(ctx, Authenticate_GenerateJWT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticateClient) ValidateJWT(ctx context.Context, in *ValidateJWTReq, opts ...grpc.CallOption) (*ValidateJWTResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateJWTResp)
	err := c.cc.Invoke(ctx, Authenticate_ValidateJWT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticateClient) GenerateSignedUrl(ctx context.Context, in *GenerateSignedUrlReq, opts ...grpc.CallOption) (*GenerateSignedUrlResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateSignedUrlResp)
	err := c.cc.Invoke(ctx, Authenticate_GenerateSignedUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticateClient) ValidateSignedUrl(ctx context.Context, in *ValidateSignedUrlReq, opts ...grpc.CallOption) (*ValidateSignedUrlResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateSignedUrlResp)
	err := c.cc.Invoke(ctx, Authenticate_ValidateSignedUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticateServer is the server API for Authenticate service.
// All implementations must embed UnimplementedAuthenticateServer
// for forward compatibility.
type AuthenticateServer interface {
	GenerateJWT(context.Context, *GenerateJWTReq) (*GenerateJWTResp, error)
	ValidateJWT(context.Context, *ValidateJWTReq) (*ValidateJWTResp, error)
	GenerateSignedUrl(context.Context, *GenerateSignedUrlReq) (*GenerateSignedUrlResp, error)
	ValidateSignedUrl(context.Context, *ValidateSignedUrlReq) (*ValidateSignedUrlResp, error)
	mustEmbedUnimplementedAuthenticateServer()
}

// UnimplementedAuthenticateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthenticateServer struct{}

func (UnimplementedAuthenticateServer) GenerateJWT(context.Context, *GenerateJWTReq) (*GenerateJWTResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateJWT not implemented")
}
func (UnimplementedAuthenticateServer) ValidateJWT(context.Context, *ValidateJWTReq) (*ValidateJWTResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateJWT not implemented")
}
func (UnimplementedAuthenticateServer) GenerateSignedUrl(context.Context, *GenerateSignedUrlReq) (*GenerateSignedUrlResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateSignedUrl not implemented")
}
func (UnimplementedAuthenticateServer) ValidateSignedUrl(context.Context, *ValidateSignedUrlReq) (*ValidateSignedUrlResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateSignedUrl not implemented")
}
func (UnimplementedAuthenticateServer) mustEmbedUnimplementedAuthenticateServer() {}
func (UnimplementedAuthenticateServer) testEmbeddedByValue()                      {}

// UnsafeAuthenticateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthenticateServer will
// result in compilation errors.
type UnsafeAuthenticateServer interface {
	mustEmbedUnimplementedAuthenticateServer()
}

func RegisterAuthenticateServer(s grpc.ServiceRegistrar, srv AuthenticateServer) {
	// If the following call pancis, it indicates UnimplementedAuthenticateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Authenticate_ServiceDesc, srv)
}

func _Authenticate_GenerateJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateJWTReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticateServer).GenerateJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authenticate_GenerateJWT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticateServer).GenerateJWT(ctx, req.(*GenerateJWTReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authenticate_ValidateJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateJWTReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticateServer).ValidateJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authenticate_ValidateJWT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticateServer).ValidateJWT(ctx, req.(*ValidateJWTReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authenticate_GenerateSignedUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateSignedUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticateServer).GenerateSignedUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authenticate_GenerateSignedUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticateServer).GenerateSignedUrl(ctx, req.(*GenerateSignedUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authenticate_ValidateSignedUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateSignedUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticateServer).ValidateSignedUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authenticate_ValidateSignedUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticateServer).ValidateSignedUrl(ctx, req.(*ValidateSignedUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Authenticate_ServiceDesc is the grpc.ServiceDesc for Authenticate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Authenticate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Authenticate",
	HandlerType: (*AuthenticateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateJWT",
			Handler:    _Authenticate_GenerateJWT_Handler,
		},
		{
			MethodName: "ValidateJWT",
			Handler:    _Authenticate_ValidateJWT_Handler,
		},
		{
			MethodName: "GenerateSignedUrl",
			Handler:    _Authenticate_GenerateSignedUrl_Handler,
		},
		{
			MethodName: "ValidateSignedUrl",
			Handler:    _Authenticate_ValidateSignedUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
