// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: users.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UsersInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        []int64                `protobuf:"varint,1,rep,packed,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersInfoReq) Reset() {
	*x = UsersInfoReq{}
	mi := &file_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersInfoReq) ProtoMessage() {}

func (x *UsersInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersInfoReq.ProtoReflect.Descriptor instead.
func (*UsersInfoReq) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{0}
}

func (x *UsersInfoReq) GetUserID() []int64 {
	if x != nil {
		return x.UserID
	}
	return nil
}

type UsersInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          []*Info                `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	Err           *Error                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersInfoResp) Reset() {
	*x = UsersInfoResp{}
	mi := &file_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersInfoResp) ProtoMessage() {}

func (x *UsersInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersInfoResp.ProtoReflect.Descriptor instead.
func (*UsersInfoResp) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{1}
}

func (x *UsersInfoResp) GetInfo() []*Info {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *UsersInfoResp) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

type Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Surname       string                 `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Info) Reset() {
	*x = Info{}
	mi := &file_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{2}
}

func (x *Info) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Info) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Info) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{3}
}

func (x *Error) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LastReadPostsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	Err           *Error                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastReadPostsResp) Reset() {
	*x = LastReadPostsResp{}
	mi := &file_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastReadPostsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastReadPostsResp) ProtoMessage() {}

func (x *LastReadPostsResp) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastReadPostsResp.ProtoReflect.Descriptor instead.
func (*LastReadPostsResp) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{4}
}

func (x *LastReadPostsResp) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *LastReadPostsResp) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{5}
}

func (x *Post) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Post) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type LastReadPostsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastReadPostsReq) Reset() {
	*x = LastReadPostsReq{}
	mi := &file_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastReadPostsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastReadPostsReq) ProtoMessage() {}

func (x *LastReadPostsReq) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastReadPostsReq.ProtoReflect.Descriptor instead.
func (*LastReadPostsReq) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{6}
}

func (x *LastReadPostsReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type SendPostNotificationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderID      int64                  `protobuf:"varint,1,opt,name=senderID,proto3" json:"senderID,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPostNotificationReq) Reset() {
	*x = SendPostNotificationReq{}
	mi := &file_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPostNotificationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPostNotificationReq) ProtoMessage() {}

func (x *SendPostNotificationReq) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPostNotificationReq.ProtoReflect.Descriptor instead.
func (*SendPostNotificationReq) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{7}
}

func (x *SendPostNotificationReq) GetSenderID() int64 {
	if x != nil {
		return x.SenderID
	}
	return 0
}

func (x *SendPostNotificationReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendPostNotificationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           *Error                 `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPostNotificationResp) Reset() {
	*x = SendPostNotificationResp{}
	mi := &file_users_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPostNotificationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPostNotificationResp) ProtoMessage() {}

func (x *SendPostNotificationResp) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPostNotificationResp.ProtoReflect.Descriptor instead.
func (*SendPostNotificationResp) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{8}
}

func (x *SendPostNotificationResp) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

type SendNotificationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderID      int64                  `protobuf:"varint,1,opt,name=senderID,proto3" json:"senderID,omitempty"`
	ReceiversIDs  []int64                `protobuf:"varint,2,rep,packed,name=receiversIDs,proto3" json:"receiversIDs,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationReq) Reset() {
	*x = SendNotificationReq{}
	mi := &file_users_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationReq) ProtoMessage() {}

func (x *SendNotificationReq) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationReq.ProtoReflect.Descriptor instead.
func (*SendNotificationReq) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{9}
}

func (x *SendNotificationReq) GetSenderID() int64 {
	if x != nil {
		return x.SenderID
	}
	return 0
}

func (x *SendNotificationReq) GetReceiversIDs() []int64 {
	if x != nil {
		return x.ReceiversIDs
	}
	return nil
}

func (x *SendNotificationReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendNotificationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           *Error                 `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationResp) Reset() {
	*x = SendNotificationResp{}
	mi := &file_users_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResp) ProtoMessage() {}

func (x *SendNotificationResp) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResp.ProtoReflect.Descriptor instead.
func (*SendNotificationResp) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{10}
}

func (x *SendNotificationResp) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

var File_users_proto protoreflect.FileDescriptor

const file_users_proto_rawDesc = "" +
	"\n" +
	"\vusers.proto\x12\x05users\"&\n" +
	"\fUsersInfoReq\x12\x16\n" +
	"\x06UserID\x18\x01 \x03(\x03R\x06UserID\"P\n" +
	"\rUsersInfoResp\x12\x1f\n" +
	"\x04info\x18\x01 \x03(\v2\v.users.InfoR\x04info\x12\x1e\n" +
	"\x03err\x18\x02 \x01(\v2\f.users.ErrorR\x03err\"J\n" +
	"\x04Info\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x03 \x01(\tR\asurname\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"V\n" +
	"\x11LastReadPostsResp\x12!\n" +
	"\x05posts\x18\x01 \x03(\v2\v.users.PostR\x05posts\x12\x1e\n" +
	"\x03err\x18\x02 \x01(\v2\f.users.ErrorR\x03err\".\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\x03R\x06userID\"*\n" +
	"\x10LastReadPostsReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x03R\x06userID\"O\n" +
	"\x17SendPostNotificationReq\x12\x1a\n" +
	"\bsenderID\x18\x01 \x01(\x03R\bsenderID\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\":\n" +
	"\x18SendPostNotificationResp\x12\x1e\n" +
	"\x03err\x18\x01 \x01(\v2\f.users.ErrorR\x03err\"o\n" +
	"\x13SendNotificationReq\x12\x1a\n" +
	"\bsenderID\x18\x01 \x01(\x03R\bsenderID\x12\"\n" +
	"\freceiversIDs\x18\x02 \x03(\x03R\freceiversIDs\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"6\n" +
	"\x14SendNotificationResp\x12\x1e\n" +
	"\x03err\x18\x01 \x01(\v2\f.users.ErrorR\x03err2\xb1\x02\n" +
	"\x05Users\x128\n" +
	"\tUsersInfo\x12\x13.users.UsersInfoReq\x1a\x14.users.UsersInfoResp\"\x00\x12D\n" +
	"\rLastReadPosts\x12\x17.users.LastReadPostsReq\x1a\x18.users.LastReadPostsResp\"\x00\x12Y\n" +
	"\x14SendPostNotification\x12\x1e.users.SendPostNotificationReq\x1a\x1f.users.SendPostNotificationResp\"\x00\x12M\n" +
	"\x10SendNotification\x12\x1a.users.SendNotificationReq\x1a\x1b.users.SendNotificationResp\"\x00B\x0eZ\fapi/pb/usersb\x06proto3"

var (
	file_users_proto_rawDescOnce sync.Once
	file_users_proto_rawDescData []byte
)

func file_users_proto_rawDescGZIP() []byte {
	file_users_proto_rawDescOnce.Do(func() {
		file_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)))
	})
	return file_users_proto_rawDescData
}

var file_users_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_users_proto_goTypes = []any{
	(*UsersInfoReq)(nil),             // 0: users.UsersInfoReq
	(*UsersInfoResp)(nil),            // 1: users.UsersInfoResp
	(*Info)(nil),                     // 2: users.Info
	(*Error)(nil),                    // 3: users.Error
	(*LastReadPostsResp)(nil),        // 4: users.LastReadPostsResp
	(*Post)(nil),                     // 5: users.Post
	(*LastReadPostsReq)(nil),         // 6: users.LastReadPostsReq
	(*SendPostNotificationReq)(nil),  // 7: users.SendPostNotificationReq
	(*SendPostNotificationResp)(nil), // 8: users.SendPostNotificationResp
	(*SendNotificationReq)(nil),      // 9: users.SendNotificationReq
	(*SendNotificationResp)(nil),     // 10: users.SendNotificationResp
}
var file_users_proto_depIdxs = []int32{
	2,  // 0: users.UsersInfoResp.info:type_name -> users.Info
	3,  // 1: users.UsersInfoResp.err:type_name -> users.Error
	5,  // 2: users.LastReadPostsResp.posts:type_name -> users.Post
	3,  // 3: users.LastReadPostsResp.err:type_name -> users.Error
	3,  // 4: users.SendPostNotificationResp.err:type_name -> users.Error
	3,  // 5: users.SendNotificationResp.err:type_name -> users.Error
	0,  // 6: users.Users.UsersInfo:input_type -> users.UsersInfoReq
	6,  // 7: users.Users.LastReadPosts:input_type -> users.LastReadPostsReq
	7,  // 8: users.Users.SendPostNotification:input_type -> users.SendPostNotificationReq
	9,  // 9: users.Users.SendNotification:input_type -> users.SendNotificationReq
	1,  // 10: users.Users.UsersInfo:output_type -> users.UsersInfoResp
	4,  // 11: users.Users.LastReadPosts:output_type -> users.LastReadPostsResp
	8,  // 12: users.Users.SendPostNotification:output_type -> users.SendPostNotificationResp
	10, // 13: users.Users.SendNotification:output_type -> users.SendNotificationResp
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_users_proto_init() }
func file_users_proto_init() {
	if File_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_proto_goTypes,
		DependencyIndexes: file_users_proto_depIdxs,
		MessageInfos:      file_users_proto_msgTypes,
	}.Build()
	File_users_proto = out.File
	file_users_proto_goTypes = nil
	file_users_proto_depIdxs = nil
}
