// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: users.proto

package users

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Users_UsersInfo_FullMethodName            = "/users.Users/UsersInfo"
	Users_LastReadPosts_FullMethodName        = "/users.Users/LastReadPosts"
	Users_SendPostNotification_FullMethodName = "/users.Users/SendPostNotification"
	Users_SendNotification_FullMethodName     = "/users.Users/SendNotification"
)

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsersClient interface {
	UsersInfo(ctx context.Context, in *UsersInfoReq, opts ...grpc.CallOption) (*UsersInfoResp, error)
	LastReadPosts(ctx context.Context, in *LastReadPostsReq, opts ...grpc.CallOption) (*LastReadPostsResp, error)
	SendPostNotification(ctx context.Context, in *SendPostNotificationReq, opts ...grpc.CallOption) (*SendPostNotificationResp, error)
	SendNotification(ctx context.Context, in *SendNotificationReq, opts ...grpc.CallOption) (*SendNotificationResp, error)
}

type usersClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersClient(cc grpc.ClientConnInterface) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) UsersInfo(ctx context.Context, in *UsersInfoReq, opts ...grpc.CallOption) (*UsersInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsersInfoResp)
	err := c.cc.Invoke(ctx, Users_UsersInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) LastReadPosts(ctx context.Context, in *LastReadPostsReq, opts ...grpc.CallOption) (*LastReadPostsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LastReadPostsResp)
	err := c.cc.Invoke(ctx, Users_LastReadPosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) SendPostNotification(ctx context.Context, in *SendPostNotificationReq, opts ...grpc.CallOption) (*SendPostNotificationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendPostNotificationResp)
	err := c.cc.Invoke(ctx, Users_SendPostNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) SendNotification(ctx context.Context, in *SendNotificationReq, opts ...grpc.CallOption) (*SendNotificationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendNotificationResp)
	err := c.cc.Invoke(ctx, Users_SendNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
// All implementations must embed UnimplementedUsersServer
// for forward compatibility.
type UsersServer interface {
	UsersInfo(context.Context, *UsersInfoReq) (*UsersInfoResp, error)
	LastReadPosts(context.Context, *LastReadPostsReq) (*LastReadPostsResp, error)
	SendPostNotification(context.Context, *SendPostNotificationReq) (*SendPostNotificationResp, error)
	SendNotification(context.Context, *SendNotificationReq) (*SendNotificationResp, error)
	mustEmbedUnimplementedUsersServer()
}

// UnimplementedUsersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUsersServer struct{}

func (UnimplementedUsersServer) UsersInfo(context.Context, *UsersInfoReq) (*UsersInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsersInfo not implemented")
}
func (UnimplementedUsersServer) LastReadPosts(context.Context, *LastReadPostsReq) (*LastReadPostsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LastReadPosts not implemented")
}
func (UnimplementedUsersServer) SendPostNotification(context.Context, *SendPostNotificationReq) (*SendPostNotificationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPostNotification not implemented")
}
func (UnimplementedUsersServer) SendNotification(context.Context, *SendNotificationReq) (*SendNotificationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendNotification not implemented")
}
func (UnimplementedUsersServer) mustEmbedUnimplementedUsersServer() {}
func (UnimplementedUsersServer) testEmbeddedByValue()               {}

// UnsafeUsersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsersServer will
// result in compilation errors.
type UnsafeUsersServer interface {
	mustEmbedUnimplementedUsersServer()
}

func RegisterUsersServer(s grpc.ServiceRegistrar, srv UsersServer) {
	// If the following call pancis, it indicates UnimplementedUsersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Users_ServiceDesc, srv)
}

func _Users_UsersInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UsersInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_UsersInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UsersInfo(ctx, req.(*UsersInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_LastReadPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LastReadPostsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).LastReadPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_LastReadPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).LastReadPosts(ctx, req.(*LastReadPostsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_SendPostNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPostNotificationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).SendPostNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_SendPostNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).SendPostNotification(ctx, req.(*SendPostNotificationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_SendNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendNotificationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).SendNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_SendNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).SendNotification(ctx, req.(*SendNotificationReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Users_ServiceDesc is the grpc.ServiceDesc for Users service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Users_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UsersInfo",
			Handler:    _Users_UsersInfo_Handler,
		},
		{
			MethodName: "LastReadPosts",
			Handler:    _Users_LastReadPosts_Handler,
		},
		{
			MethodName: "SendPostNotification",
			Handler:    _Users_SendPostNotification_Handler,
		},
		{
			MethodName: "SendNotification",
			Handler:    _Users_SendNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users.proto",
}
