// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.18.0
// source: api/pb/auth.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateJWTReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
}

func (x *GenerateJWTReq) Reset() {
	*x = GenerateJWTReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateJWTReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateJWTReq) ProtoMessage() {}

func (x *GenerateJWTReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateJWTReq.ProtoReflect.Descriptor instead.
func (*GenerateJWTReq) Descriptor() ([]byte, []int) {
	return file_api_pb_auth_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateJWTReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GenerateJWTReq) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type GenerateJWTResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GenerateJWTResp) Reset() {
	*x = GenerateJWTResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateJWTResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateJWTResp) ProtoMessage() {}

func (x *GenerateJWTResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateJWTResp.ProtoReflect.Descriptor instead.
func (*GenerateJWTResp) Descriptor() ([]byte, []int) {
	return file_api_pb_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateJWTResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateJWTReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ValidateJWTReq) Reset() {
	*x = ValidateJWTReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateJWTReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateJWTReq) ProtoMessage() {}

func (x *ValidateJWTReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateJWTReq.ProtoReflect.Descriptor instead.
func (*ValidateJWTReq) Descriptor() ([]byte, []int) {
	return file_api_pb_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateJWTReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateJWTResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
}

func (x *ValidateJWTResp) Reset() {
	*x = ValidateJWTResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_auth_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateJWTResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateJWTResp) ProtoMessage() {}

func (x *ValidateJWTResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_auth_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateJWTResp.ProtoReflect.Descriptor instead.
func (*ValidateJWTResp) Descriptor() ([]byte, []int) {
	return file_api_pb_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateJWTResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ValidateJWTResp) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

var File_api_pb_auth_proto protoreflect.FileDescriptor

var file_api_pb_auth_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x0e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4a,
	0x57, 0x54, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x22, 0x27, 0x0a, 0x0f, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4a, 0x57, 0x54, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x26, 0x0a, 0x0e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x4a, 0x57, 0x54, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x37, 0x0a, 0x0f,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x4a, 0x57, 0x54, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x32, 0x76, 0x0a, 0x0c, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x32, 0x0a, 0x0b, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x4a, 0x57, 0x54, 0x12, 0x0f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4a,
	0x57, 0x54, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x4a, 0x57, 0x54, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0b, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x4a, 0x57, 0x54, 0x12, 0x0f, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x4a, 0x57, 0x54, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x4a, 0x57, 0x54, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x08, 0x5a,
	0x06, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_pb_auth_proto_rawDescOnce sync.Once
	file_api_pb_auth_proto_rawDescData = file_api_pb_auth_proto_rawDesc
)

func file_api_pb_auth_proto_rawDescGZIP() []byte {
	file_api_pb_auth_proto_rawDescOnce.Do(func() {
		file_api_pb_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_pb_auth_proto_rawDescData)
	})
	return file_api_pb_auth_proto_rawDescData
}

var file_api_pb_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_pb_auth_proto_goTypes = []interface{}{
	(*GenerateJWTReq)(nil),  // 0: GenerateJWTReq
	(*GenerateJWTResp)(nil), // 1: GenerateJWTResp
	(*ValidateJWTReq)(nil),  // 2: ValidateJWTReq
	(*ValidateJWTResp)(nil), // 3: ValidateJWTResp
}
var file_api_pb_auth_proto_depIdxs = []int32{
	0, // 0: Authenticate.GenerateJWT:input_type -> GenerateJWTReq
	2, // 1: Authenticate.ValidateJWT:input_type -> ValidateJWTReq
	1, // 2: Authenticate.GenerateJWT:output_type -> GenerateJWTResp
	3, // 3: Authenticate.ValidateJWT:output_type -> ValidateJWTResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_pb_auth_proto_init() }
func file_api_pb_auth_proto_init() {
	if File_api_pb_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_pb_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateJWTReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateJWTResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_auth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateJWTReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_auth_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateJWTResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_pb_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pb_auth_proto_goTypes,
		DependencyIndexes: file_api_pb_auth_proto_depIdxs,
		MessageInfos:      file_api_pb_auth_proto_msgTypes,
	}.Build()
	File_api_pb_auth_proto = out.File
	file_api_pb_auth_proto_rawDesc = nil
	file_api_pb_auth_proto_goTypes = nil
	file_api_pb_auth_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthenticateClient is the client API for Authenticate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticateClient interface {
	GenerateJWT(ctx context.Context, in *GenerateJWTReq, opts ...grpc.CallOption) (*GenerateJWTResp, error)
	ValidateJWT(ctx context.Context, in *ValidateJWTReq, opts ...grpc.CallOption) (*ValidateJWTResp, error)
}

type authenticateClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticateClient(cc grpc.ClientConnInterface) AuthenticateClient {
	return &authenticateClient{cc}
}

func (c *authenticateClient) GenerateJWT(ctx context.Context, in *GenerateJWTReq, opts ...grpc.CallOption) (*GenerateJWTResp, error) {
	out := new(GenerateJWTResp)
	err := c.cc.Invoke(ctx, "/Authenticate/GenerateJWT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticateClient) ValidateJWT(ctx context.Context, in *ValidateJWTReq, opts ...grpc.CallOption) (*ValidateJWTResp, error) {
	out := new(ValidateJWTResp)
	err := c.cc.Invoke(ctx, "/Authenticate/ValidateJWT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticateServer is the server API for Authenticate service.
type AuthenticateServer interface {
	GenerateJWT(context.Context, *GenerateJWTReq) (*GenerateJWTResp, error)
	ValidateJWT(context.Context, *ValidateJWTReq) (*ValidateJWTResp, error)
}

// UnimplementedAuthenticateServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticateServer struct {
}

func (*UnimplementedAuthenticateServer) GenerateJWT(context.Context, *GenerateJWTReq) (*GenerateJWTResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateJWT not implemented")
}
func (*UnimplementedAuthenticateServer) ValidateJWT(context.Context, *ValidateJWTReq) (*ValidateJWTResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateJWT not implemented")
}

func RegisterAuthenticateServer(s *grpc.Server, srv AuthenticateServer) {
	s.RegisterService(&_Authenticate_serviceDesc, srv)
}

func _Authenticate_GenerateJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateJWTReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticateServer).GenerateJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Authenticate/GenerateJWT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticateServer).GenerateJWT(ctx, req.(*GenerateJWTReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authenticate_ValidateJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateJWTReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticateServer).ValidateJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Authenticate/ValidateJWT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticateServer).ValidateJWT(ctx, req.(*ValidateJWTReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authenticate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Authenticate",
	HandlerType: (*AuthenticateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateJWT",
			Handler:    _Authenticate_GenerateJWT_Handler,
		},
		{
			MethodName: "ValidateJWT",
			Handler:    _Authenticate_ValidateJWT_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/pb/auth.proto",
}
