FROM python:3.13
RUN --mount=type=cache,target=/root/.cache/pip \
    python -m pip install tensorflow flask tensorflow_datasets keras
COPY ./ai .
EXPOSE 8000
CMD ["python3", "main.py", "--host=0.0.0.0", "--port=8000"]

