FROM ghcr.io/benoitc/gunicorn:24.1.0

RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=bind,source=./ai/requirements.txt,target=requirements.txt \
    python -m pip install -r requirements.txt

COPY --chown=gunicorn:gunicorn ./ai .
EXPOSE 8000

CMD ["main:main()", "--workers", "4"]
