FROM python:3.13
RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=bind,source=./ai/requirements.txt,target=requirements.txt \
    python -m pip install -r requirements.txt
COPY ./ai .
EXPOSE 8000
CMD ["python3", "main.py", "--host=0.0.0.0", "--port=8000"]

