FROM ghcr.io/benoitc/gunicorn:24.1.0

RUN --mount=type=cache,target=/root/.cache/pip \
    python -m pip install tensorflow flask tensorflow_datasets keras
COPY --chown=gunicorn:gunicorn ./ai .
EXPOSE 8000

CMD ["main:main()", "--workers", "4"]
